"""Coverage results — ÖBB alignment heatmap (per-cell itineraries + score + tier).

PR-196a. Adds three nullable columns to `network_coverage_results` so the
matrix UI can render a graduated agreement heatmap (agree / mostly /
partial / disagree / no_overlap / one_sided / no_service / no_data)
instead of the binary "Show only where ÖBB disagrees" filter PR-E
shipped — that filter hid every cell whose `external_ok != true`, which
includes every status='ok' cell (those skipped the verify sweep entirely
in PR-E and therefore have NULL external_ok), producing the
white-matrix bug operators reported.

Schema-design notes:
  - `external_itineraries` is JSONB so the cell-trips modal can render
    the ÖBB side-by-side against VIATOR without re-querying HAFAS. The
    payload is the normalised per-trip list shape app/journey/hafas_client
    already emits (legs[], departure_at, arrival_at, route_short_name,
    etc.) — same dialect VIATOR trips use, so the modal's existing
    leg-renderer reads both without a branch.
  - `external_alignment_score` is FLOAT (0.0-1.0). NULL means "no
    score computable" — distinct from 0.0 which means "scored, both
    sides have trips, zero overlap".
  - `external_alignment_tier` is VARCHAR(32) carrying the human-readable
    bucket the UI uses to colour the cell. Eight valid values; not
    CHECK-constrained because the runner is the only writer and adding
    a tier (e.g. 'one_sided_motis' for a future MOTIS comparison) should
    not need a schema migration.

Backfill: every existing row gets NULL across all three columns. The
matrix UI's new tier-aware filter renders NULL as `no_data` (light
grey, unchecked-by-default in the dropdown) so legacy rows survive
visually and the operator can hide them with one click.

Revision ID: 20260701_0900_oebb_alignment
Revises: 20260630_1500_coverage_window
Create Date: 2026-07-01 09:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260701_0900_oebb_alignment"
down_revision: str | Sequence[str] | None = "20260630_1500_coverage_window"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # PR-196a — per-cell ÖBB itinerary capture + alignment score / tier.
    # All three nullable, no server_default — legacy rows read as NULL
    # (renders as `no_data` tier in the matrix UI).
    op.add_column(
        "network_coverage_results",
        sa.Column("external_itineraries", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "network_coverage_results",
        sa.Column("external_alignment_score", sa.Float(), nullable=True),
    )
    op.add_column(
        "network_coverage_results",
        sa.Column("external_alignment_tier", sa.String(length=32), nullable=True),
    )


def downgrade() -> None:
    # Reverse order: drop newest first — symmetric with upgrade so a
    # future autogenerated diff against the prior revision matches.
    op.drop_column("network_coverage_results", "external_alignment_tier")
    op.drop_column("network_coverage_results", "external_alignment_score")
    op.drop_column("network_coverage_results", "external_itineraries")
