"""Generate per-session compose + nginx fragments and (optionally) reload them.

Pattern A from spec §4.4: regenerate `docker/docker-compose.sessions.yml` and
`docker/nginx/sessions.conf` whenever the set of sessions changes, then call
`docker compose up -d` and `nginx -s reload`.

Implementation here is the **generator + dry-run trigger**. The actual
`docker compose up` call is invoked from the worker (which already has the
docker socket mounted) — see `app/worker.py`.
"""

from __future__ import annotations

import logging
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session as DbSession

from .models import Session as SessionRow
from .models.sessions import SessionState

log = logging.getLogger(__name__)

COMPOSE_FRAGMENT = Path("/data/generated/docker-compose.sessions.yml")
NGINX_FRAGMENT = Path("/data/generated/nginx-sessions.conf")


_COMPOSE_HEADER = """# Generated by VIATOR sessions orchestrator. DO NOT EDIT BY HAND.
# Regenerated whenever a session is created / archived / deleted.

services:
"""

# NB: braces in env-var defaults need to be doubled in this Python format
# string so str.format leaves them as `${VIATOR_VERSION:-latest}` literally
# rather than interpreting them as a format spec.
_OTP_SVC_TEMPLATE = """  otp-{sid}:
    image: ghcr.io/top-phe/viator-otp:${{VIATOR_VERSION:-latest}}
    build:
      # Path is relative to THIS generated file's location
      # (docker/generated/docker-compose.sessions.yml), so `../otp`
      # resolves to docker/otp/ — the same source used by the main
      # docker-compose.yml's otp-build service.
      context: ../otp
    restart: unless-stopped
    environment:
      OTP_MODE: serve
      # Per-session subdirectory under the shared graphs volume — the
      # entrypoint loads $OTP_GRAPH_DIR/current/graph.obj.
      OTP_GRAPH_DIR: /var/otp/graph/{sid}
      OTP_HEAP: "{heap}"
    volumes:
      # Shared graphs volume — same one the worker writes to. The worker
      # creates per-session subdirs under /data/graphs/<sid>/<timestamp>/
      # with `current` symlinks (relative — see app/worker.py). The otp
      # serving container reads the same files via /var/otp/graph/<sid>/.
      - graphs:/var/otp/graph:ro
    labels:
      viator.session_id: "{sid}"
      viator.category: "{category}"

"""

# No per-session volumes are declared — sessions share the `graphs` and
# `inbox` volumes already declared in the main docker-compose.yml.
# The empty `volumes: {}` mapping below keeps the rendered fragment
# valid YAML even when there are zero serving sessions.
_VOLUMES_HEADER = "volumes: {}\n"


def render_compose(sessions: list[SessionRow]) -> str:
    """Render the per-session compose fragment for all serving sessions."""
    services = "".join(
        _OTP_SVC_TEMPLATE.format(
            sid=s.id,
            heap=(s.config or {}).get("otp_heap", "4g"),
            category=s.category,
        )
        for s in sessions
        if s.state == SessionState.SERVING.value
    )
    return _COMPOSE_HEADER + (services or "  # (no serving sessions)\n") + "\n" + _VOLUMES_HEADER


def render_nginx(sessions: list[SessionRow]) -> str:
    """nginx location blocks proxying /otp/<sid>/ to otp-<sid>:8080."""
    parts = ["# Generated by VIATOR sessions orchestrator. DO NOT EDIT BY HAND.\n"]
    for s in sessions:
        if s.state != SessionState.SERVING.value:
            continue
        parts.append(
            f"location /otp/{s.id}/ {{\n"
            f"    proxy_pass http://otp-{s.id}:8080/otp/;\n"
            f"    proxy_set_header Host $host;\n"
            f"}}\n"
        )
    return "".join(parts)


def regenerate(db: DbSession, *, output_dir: Path | None = None) -> dict[str, Path]:
    """Write both fragments to disk. Returns the paths written.

    Caller is responsible for triggering `docker compose up -d` + nginx reload.
    """
    out_compose = (output_dir / "docker-compose.sessions.yml") if output_dir else COMPOSE_FRAGMENT
    out_nginx = (output_dir / "nginx-sessions.conf") if output_dir else NGINX_FRAGMENT

    sessions = db.execute(select(SessionRow)).scalars().all()
    out_compose.parent.mkdir(parents=True, exist_ok=True)
    out_compose.write_text(render_compose(list(sessions)), encoding="utf-8")
    out_nginx.parent.mkdir(parents=True, exist_ok=True)
    out_nginx.write_text(render_nginx(list(sessions)), encoding="utf-8")

    log.info(
        "sessions orchestrator: wrote %s and %s for %d sessions",
        out_compose,
        out_nginx,
        len(sessions),
    )
    return {"compose": out_compose, "nginx": out_nginx}
