"""Generate per-session compose + nginx fragments and (optionally) reload them.

Pattern A from spec §4.4: regenerate `docker/docker-compose.sessions.yml` and
`docker/nginx/sessions.conf` whenever the set of sessions changes, then call
`docker compose up -d` and `nginx -s reload`.

Implementation here is the **generator + dry-run trigger**. The actual
`docker compose up` call is invoked from the worker (which already has the
docker socket mounted) — see `app/worker.py`.
"""

from __future__ import annotations

import logging
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session as DbSession

from .models import Session as SessionRow
from .models.sessions import SessionState

log = logging.getLogger(__name__)

COMPOSE_FRAGMENT = Path("/data/generated/docker-compose.sessions.yml")
NGINX_FRAGMENT = Path("/data/generated/nginx-sessions.conf")


_COMPOSE_HEADER = """# Generated by VIATOR sessions orchestrator. DO NOT EDIT BY HAND.
# Regenerated whenever a session is created / archived / deleted.

services:
"""

# NB: braces in env-var defaults need to be doubled in this Python format
# string so str.format leaves them as `${VIATOR_VERSION:-latest}` literally
# rather than interpreting them as a format spec.
#
# PR #32 (audit row #32): the `healthcheck` block is rendered per-session
# so operators can pick a `start_period` matching their graph's actual
# load-time. The pre-PR-#32 baked HEALTHCHECK in docker/otp/Dockerfile
# was hardcoded to 120s, which restart-loops the container on graphs
# that take >2 min to do their Raptor mapping (which is most multi-NAP
# or Europe-wide sessions — surfaced 2026-05-11 on nap-fr-rail with SBB).
# The Dockerfile's HEALTHCHECK directive is now dropped; this fragment
# owns it.
_OTP_SVC_TEMPLATE = """  otp-{sid}:
    image: ghcr.io/top-phe/viator-otp:${{VIATOR_VERSION:-latest}}
    build:
      # Path is relative to THIS generated file's location
      # (docker/generated/docker-compose.sessions.yml), so `../otp`
      # resolves to docker/otp/ — the same source used by the main
      # docker-compose.yml's otp-build service.
      context: ../otp
    restart: unless-stopped
    environment:
      OTP_MODE: serve
      # Per-session subdirectory under the shared graphs volume — the
      # entrypoint loads $OTP_GRAPH_DIR/current/graph.obj.
      OTP_GRAPH_DIR: /var/otp/graph/{sid}
      OTP_HEAP: "{heap}"
    volumes:
      # Shared graphs volume — same one the worker writes to. The worker
      # creates per-session subdirs under /data/graphs/<sid>/<timestamp>/
      # with `current` symlinks (relative — see app/worker.py). The otp
      # serving container reads the same files via /var/otp/graph/<sid>/.
      - graphs:/var/otp/graph:ro
    healthcheck:
      # `start_period` is the grace window during which a failing
      # /otp/ probe doesn't count as unhealthy. The default 300s (5 min)
      # is comfortable for France-wide multi-NAP sessions; operators with
      # bigger graphs override via session.config.otp_serve_start_period.
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/otp/ || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: {start_period}s
      retries: 3
    labels:
      viator.session_id: "{sid}"
      viator.category: "{category}"

"""

# P1 MOTIS — per-session MOTIS service. Same shape as the OTP block so
# the rest of the orchestration (regenerate trigger, nginx routing,
# reload sentinel) is unchanged. MOTIS data lives under the SAME shared
# `graphs` volume but at a separate per-session subtree (`motis/<sid>/`
# vs `<sid>/` for OTP) so a single session never has both. The worker's
# motis-build step writes `graphs/motis/<sid>/current/` and the serve
# container reads it via the `--data` flag (NOT `--config` — `motis server`
# takes a data directory, not a config file).
#
# Phase-0.5 spike findings (run 2026-06-19, nap-sp-rail on the VPS) that
# shaped this template:
#   * Healthcheck targets `GET /` which returns 200 (the splash page MOTIS
#     prints on boot). `/api/v6/` returns 400 — `curl -f` would treat that
#     as a failure and crash-loop the container.
#   * Container's default user is `motis`; the `user: "0:0"` override is
#     needed so the serve process can map the read-only data dir without
#     uid-mismatch quirks (the worker writes the data dir as root via its
#     own `--user 0:0` runs).
_MOTIS_SVC_TEMPLATE = """  motis-{sid}:
    image: ghcr.io/motis-project/motis:${{MOTIS_VERSION:-latest}}
    restart: unless-stopped
    user: "0:0"
    volumes:
      # Shared graphs volume — the worker writes per-session MOTIS
      # imported data under graphs/motis/<sid>/current/; this mount
      # surfaces it at /var/motis-graphs inside the container, read-only.
      - graphs:/var/motis-graphs:ro
    command: ["/motis", "server", "--data", "/var/motis-graphs/motis/{sid}/current"]
    healthcheck:
      # GET / is the cheapest 200 — Phase-0.5 spike confirmed /api/v6/* all
      # return 400 with empty params (the endpoint is alive but demanding),
      # so a curl -f probe against them would mark the container unhealthy.
      # start_period mirrors the OTP knob so operators tune big-feed import
      # times the same way for both engines.
      # Use wget (ships in the Alpine-based motis image) instead of curl —
      # the upstream ghcr.io/motis-project/motis image doesn't include curl,
      # so the previous curl-based probe always failed and every MOTIS
      # container reported (unhealthy), preventing docker from auto-
      # restarting MOTIS when the HTTP server actually died.
      test: ["CMD", "wget", "--spider", "-q", "--timeout=5", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      start_period: {start_period}s
      retries: 3
    labels:
      viator.session_id: "{sid}"
      viator.category: "{category}"
      viator.engine: "motis"

"""

# No per-session volumes are declared — sessions share the `graphs` and
# `inbox` volumes already declared in the main docker-compose.yml.
# The empty `volumes: {}` mapping below keeps the rendered fragment
# valid YAML even when there are zero serving sessions.
_VOLUMES_HEADER = "volumes: {}\n"


def render_compose(sessions: list[SessionRow]) -> str:
    """Render the per-session compose fragment for all serving sessions.

    When there are zero serving sessions, we emit `services:\n  {}` (an
    explicit empty flow-style mapping). A bare `services:` with only a
    comment underneath parses as `services: null`, and `docker compose up`
    then rejects the whole include with `services must be a mapping` —
    breaking every fresh install on the second `docker compose up` after
    the web container's _startup hook overwrites the bootstrap stub.

    P1 MOTIS — sessions with `engine='motis'` render a `motis-<sid>`
    service from the parallel template; everything else renders the
    legacy `otp-<sid>` block.
    """
    from . import otp_heap as _otp_heap
    from . import otp_start_period as _otp_start_period

    parts: list[str] = []
    for s in sessions:
        if s.state != SessionState.SERVING.value:
            continue
        engine = getattr(s, "engine", "otp") or "otp"
        if engine == "motis":
            parts.append(
                _MOTIS_SVC_TEMPLATE.format(
                    sid=s.id,
                    # MOTIS imports the full year up front; cold-start is
                    # dominated by data-mmap, not query warmup. Reuse the
                    # OTP knob so operators tune both planners the same way.
                    start_period=_otp_start_period.validate_start_period(
                        (s.config or {}).get("otp_serve_start_period")
                    ),
                    category=s.category,
                )
            )
        else:
            parts.append(
                _OTP_SVC_TEMPLATE.format(
                    sid=s.id,
                    # Serve heap: explicit operator choice from the session-edit form
                    # if set, otherwise a sensible default derived from the build
                    # heap (~1/3 of build heap, floored at 4g). This prevents the
                    # silent-4g-default trap that surfaced on 2026-05-10 — operator
                    # picks 64g build heap, build succeeds, OTP serve container
                    # crash-loops at the old hardcoded 4g default. Audit follow-up
                    # to #14 Phase 2 (the rest of the observability + operations
                    # arc that closed in v0.1.32.21).
                    heap=(s.config or {}).get("otp_heap")
                    or _otp_heap.default_serve_heap_for_build(
                        (s.config or {}).get("otp_build_heap")
                    ),
                    # Healthcheck start_period: explicit operator choice if set,
                    # otherwise 300s (5 min) — covers most graphs while keeping
                    # genuinely-stuck JVMs visible quickly. PR #32 fix for the
                    # 2026-05-11 restart-loop on nap-fr-rail with SBB included.
                    start_period=_otp_start_period.validate_start_period(
                        (s.config or {}).get("otp_serve_start_period")
                    ),
                    category=s.category,
                )
            )
    services = "".join(parts)
    return _COMPOSE_HEADER + (services or "  {}  # no serving sessions\n") + "\n" + _VOLUMES_HEADER


def render_nginx(sessions: list[SessionRow]) -> str:
    """nginx location blocks for serving sessions, routed by engine.

    v0.1.15 dynamic upstream: each block uses the variable-based
    `proxy_pass` pattern so nginx re-resolves the hostname on every
    request via Docker's embedded DNS (configured at the http level
    in `docker/nginx/nginx.conf`). This means a per-session container
    restart no longer needs an explicit `nginx -s reload` to start
    being routable again — same fix as the web upstream.

    The `rewrite ... break` is needed because the variable-based
    `proxy_pass http://$var` doesn't accept a trailing URI; we have to
    transform the request URI ourselves before nginx forwards it.

    Engine-specific routing:
      - OTP sessions   → `/otp/<sid>/foo`   → `otp-<sid>:8080/otp/foo`
      - MOTIS sessions → `/motis/<sid>/foo` → `motis-<sid>:8080/foo`
    """
    parts = ["# Generated by VIATOR sessions orchestrator. DO NOT EDIT BY HAND.\n"]
    for s in sessions:
        if s.state != SessionState.SERVING.value:
            continue
        engine = getattr(s, "engine", "otp") or "otp"
        if engine == "motis":
            parts.append(
                f"location /motis/{s.id}/ {{\n"
                f'    set $motis_upstream_{_safe_var(s.id)} "motis-{s.id}:8080";\n'
                f"    rewrite ^/motis/{s.id}/(.*)$ /$1 break;\n"
                f"    proxy_pass http://$motis_upstream_{_safe_var(s.id)};\n"
                f"    proxy_set_header Host $host;\n"
                f"}}\n"
            )
        else:
            parts.append(
                f"location /otp/{s.id}/ {{\n"
                f'    set $otp_upstream_{_safe_var(s.id)} "otp-{s.id}:8080";\n'
                f"    rewrite ^/otp/{s.id}/(.*)$ /otp/$1 break;\n"
                f"    proxy_pass http://$otp_upstream_{_safe_var(s.id)};\n"
                f"    proxy_set_header Host $host;\n"
                f"}}\n"
            )
    return "".join(parts)


def _safe_var(sid: str) -> str:
    """Sanitise a session id for use as an nginx variable suffix.

    nginx variables only accept [A-Za-z0-9_]; session ids allow `-`. We
    swap `-` → `_` so e.g. `nap-fr-rail` becomes `$otp_upstream_nap_fr_rail`.
    The session-id slug regex (`^[a-z][a-z0-9-]+$`) guarantees no other
    transformations are needed.
    """
    return sid.replace("-", "_")


def regenerate(db: DbSession, *, output_dir: Path | None = None) -> dict[str, Path]:
    """Write both fragments to disk. Returns the paths written.

    Caller is responsible for triggering `docker compose up -d` + nginx reload.
    """
    out_compose = (output_dir / "docker-compose.sessions.yml") if output_dir else COMPOSE_FRAGMENT
    out_nginx = (output_dir / "nginx-sessions.conf") if output_dir else NGINX_FRAGMENT

    sessions = db.execute(select(SessionRow)).scalars().all()
    out_compose.parent.mkdir(parents=True, exist_ok=True)
    out_compose.write_text(render_compose(list(sessions)), encoding="utf-8")
    out_nginx.parent.mkdir(parents=True, exist_ok=True)
    out_nginx.write_text(render_nginx(list(sessions)), encoding="utf-8")

    log.info(
        "sessions orchestrator: wrote %s and %s for %d sessions",
        out_compose,
        out_nginx,
        len(sessions),
    )
    return {"compose": out_compose, "nginx": out_nginx}
