"""router-config.json generation (v0.1.7).

Per-session OTP router-config.json is generated by the worker from each
provider's gtfs_rt URLs. Tests cover:

  - empty providers list yields a config without `updaters` (OTP can't
    parse `"updaters": []`)
  - one provider with all three RT URLs → three updaters with feedId
  - mixed providers (some with RT, some without) → only emit for those
    with URLs
  - feedId on each updater matches the provider id
"""

from __future__ import annotations

import json


def _render(providers):
    from app.router_config import render_router_config

    return json.loads(render_router_config(providers))


def test_empty_providers_omits_updaters_key():
    cfg = _render([])
    assert "updaters" not in cfg, "OTP rejects `updaters: []`; the key must be absent when empty"
    assert "server" in cfg
    assert "routingDefaults" in cfg


def test_routing_defaults_include_access_egress_bound():
    """OTP routes "as close as it can" to the destination by default,
    silently truncating when the destination is far from any transit
    stop. Our default tightens this so trips are refused outright
    (LOCATION_NOT_FOUND) instead of returning misleading partial routes."""
    cfg = _render([])
    bounds = cfg["routingDefaults"].get("maxAccessEgressDurationForMode")
    assert bounds is not None, "routingDefaults must include access/egress bound"
    assert (
        bounds.get("WALK") == "20m"
    ), "WALK access/egress bound is the safety net against silent truncation"


def test_provider_without_gtfs_rt_emits_no_updater():
    cfg = _render(
        [
            {
                "id": "SNCF",
                "label": "SNCF",
                "country_iso": "FR",
                "timetable": {"format": "gtfs", "url": "https://x"},
                "gtfs_rt": {},
            }
        ]
    )
    assert "updaters" not in cfg


def test_one_provider_with_three_rt_urls_emits_three_updaters():
    cfg = _render(
        [
            {
                "id": "SNCF",
                "label": "SNCF",
                "country_iso": "FR",
                "timetable": {"format": "gtfs", "url": "https://x"},
                "gtfs_rt": {
                    "alerts_url": "https://a/alerts",
                    "trip_updates_url": "https://a/trip",
                    "vehicle_positions_url": "https://a/vehicle",
                },
            },
        ]
    )
    types = [u["type"] for u in cfg["updaters"]]
    assert types == ["real-time-alerts", "stop-time-updater", "vehicle-positions"]
    for u in cfg["updaters"]:
        assert u["feedId"] == "SNCF"
        assert u["frequency"] == "1m"


def test_multiple_providers_emit_in_declared_order():
    cfg = _render(
        [
            {"id": "SNCF", "gtfs_rt": {"alerts_url": "https://a/alerts"}},
            {"id": "IDFM", "gtfs_rt": {"trip_updates_url": "https://b/trip"}},
            {"id": "TRENITALIA", "gtfs_rt": {}},  # no RT, contributes 0
        ]
    )
    feed_ids = [u["feedId"] for u in cfg["updaters"]]
    assert feed_ids == ["SNCF", "IDFM"], "provider order should be preserved; trenitalia has no RT"


def test_partial_rt_only_emits_present_keys():
    cfg = _render([{"id": "SNCF", "gtfs_rt": {"alerts_url": "https://a"}}])
    # Only alerts URL → only one updater entry
    assert len(cfg["updaters"]) == 1
    assert cfg["updaters"][0]["type"] == "real-time-alerts"
