"""router-config.json generation (v0.1.7).

Per-session OTP router-config.json is generated by the worker from each
provider's gtfs_rt URLs. Tests cover:

  - empty providers list yields a config without `updaters` (OTP can't
    parse `"updaters": []`)
  - one provider with all three RT URLs → three updaters with feedId
  - mixed providers (some with RT, some without) → only emit for those
    with URLs
  - feedId on each updater matches the provider id
"""

from __future__ import annotations

import json


def _render(providers):
    from app.router_config import render_router_config

    return json.loads(render_router_config(providers))


def test_empty_providers_omits_updaters_key():
    cfg = _render([])
    assert "updaters" not in cfg, "OTP rejects `updaters: []`; the key must be absent when empty"
    assert "server" in cfg
    assert "routingDefaults" in cfg


def test_routing_defaults_include_access_egress_bound():
    """OTP routes "as close as it can" to the destination by default,
    silently truncating when the destination is far from any transit
    stop. Our default tightens this so trips are refused outright
    (LOCATION_NOT_FOUND) instead of returning misleading partial routes.

    v0.1.24: OTP 2.9 renamed `maxAccessEgressDurationForMode` (flat,
    uppercase mode keys) to `accessEgress.maxDurationForMode` (nested,
    lowercase keys). The source migrated in commit fa61df0; this test
    was missed and asserted the old shape until the audit-2026-05
    coverage gate caught it. Both shape AND key casing are part of
    the contract — the old form silently fell back to OTP defaults.
    """
    cfg = _render([])
    access_egress = cfg["routingDefaults"].get("accessEgress")
    assert access_egress is not None, "routingDefaults must declare accessEgress (OTP 2.9 schema)"
    bounds = access_egress.get("maxDurationForMode")
    assert bounds is not None, "accessEgress must include maxDurationForMode bound"
    assert bounds.get("walk") == "20m", (
        "walk bound is the safety net against silent truncation (lowercase per OTP 2.9)"
    )


def test_provider_without_gtfs_rt_emits_no_updater():
    cfg = _render(
        [
            {
                "id": "SNCF",
                "label": "SNCF",
                "country_iso": "FR",
                "timetable": {"format": "gtfs", "url": "https://x"},
                "gtfs_rt": {},
            }
        ]
    )
    assert "updaters" not in cfg


def test_one_provider_with_three_rt_urls_emits_three_updaters():
    cfg = _render(
        [
            {
                "id": "SNCF",
                "label": "SNCF",
                "country_iso": "FR",
                "timetable": {"format": "gtfs", "url": "https://x"},
                "gtfs_rt": {
                    "alerts_url": "https://a/alerts",
                    "trip_updates_url": "https://a/trip",
                    "vehicle_positions_url": "https://a/vehicle",
                },
            },
        ]
    )
    types = [u["type"] for u in cfg["updaters"]]
    assert types == ["real-time-alerts", "stop-time-updater", "vehicle-positions"]
    for u in cfg["updaters"]:
        assert u["feedId"] == "SNCF"
        assert u["frequency"] == "1m"


def test_multiple_providers_emit_in_declared_order():
    cfg = _render(
        [
            {"id": "SNCF", "gtfs_rt": {"alerts_url": "https://a/alerts"}},
            {"id": "IDFM", "gtfs_rt": {"trip_updates_url": "https://b/trip"}},
            {"id": "TRENITALIA", "gtfs_rt": {}},  # no RT, contributes 0
        ]
    )
    feed_ids = [u["feedId"] for u in cfg["updaters"]]
    assert feed_ids == ["SNCF", "IDFM"], "provider order should be preserved; trenitalia has no RT"


def test_partial_rt_only_emits_present_keys():
    cfg = _render([{"id": "SNCF", "gtfs_rt": {"alerts_url": "https://a"}}])
    # Only alerts URL → only one updater entry
    assert len(cfg["updaters"]) == 1
    assert cfg["updaters"][0]["type"] == "real-time-alerts"


# ─────────────────────── credentials integration (v0.1.10) ───────────────────────


def _render_with_creds(providers, credentials):
    from app.router_config import render_router_config

    return json.loads(render_router_config(providers, credentials=credentials))


def test_provider_without_credential_id_emits_no_headers():
    """Pre-v0.1.10 sessions (no credential_id) must keep behaving exactly as before."""
    cfg = _render_with_creds(
        [{"id": "SNCF", "gtfs_rt": {"alerts_url": "https://a/alerts"}}],
        credentials={"some-id": ("bearer", "token", None)},
    )
    updater = cfg["updaters"][0]
    assert "headers" not in updater
    assert updater["url"] == "https://a/alerts"


def test_bearer_credential_adds_headers_on_updater():
    cfg = _render_with_creds(
        [
            {
                "id": "SNCF",
                "gtfs_rt": {"alerts_url": "https://a/alerts"},
                "gtfs_rt_credential_id": "cred-1",
            },
        ],
        credentials={"cred-1": ("bearer", "my-token", None)},
    )
    updater = cfg["updaters"][0]
    assert updater["headers"] == {"Authorization": "Bearer my-token"}
    # URL unchanged for header-style auth.
    assert updater["url"] == "https://a/alerts"


def test_query_credential_appends_param_to_url():
    cfg = _render_with_creds(
        [
            {
                "id": "SNCF",
                "gtfs_rt": {"alerts_url": "https://api.sncf.com/alerts"},
                "gtfs_rt_credential_id": "cred-1",
            },
        ],
        credentials={"cred-1": ("query", "MY_KEY", "apikey")},
    )
    updater = cfg["updaters"][0]
    assert updater["url"] == "https://api.sncf.com/alerts?apikey=MY_KEY"
    # Query auth never adds headers.
    assert "headers" not in updater


def test_one_credential_applied_to_all_three_rt_urls():
    """gtfs_rt_credential_id covers alerts + trip_updates + vehicle_positions
    on the same provider (they're virtually always on the same domain)."""
    cfg = _render_with_creds(
        [
            {
                "id": "SNCF",
                "gtfs_rt": {
                    "alerts_url": "https://a/alerts",
                    "trip_updates_url": "https://a/trip",
                    "vehicle_positions_url": "https://a/vehicle",
                },
                "gtfs_rt_credential_id": "cred-1",
            },
        ],
        credentials={"cred-1": ("header", "secret-value", "X-API-Key")},
    )
    assert len(cfg["updaters"]) == 3
    for u in cfg["updaters"]:
        assert u["headers"] == {"X-API-Key": "secret-value"}


def test_missing_credential_in_map_falls_back_to_anonymous():
    """If the worker can't decrypt a credential (e.g. JWT_SECRET rotated),
    it omits the entry from the map. Render then falls back to anonymous
    rather than crashing or refusing to emit the updater."""
    cfg = _render_with_creds(
        [
            {
                "id": "SNCF",
                "gtfs_rt": {"alerts_url": "https://a/alerts"},
                "gtfs_rt_credential_id": "missing-cred",
            },
        ],
        credentials={},  # the credential the provider points at isn't here
    )
    updater = cfg["updaters"][0]
    assert updater["url"] == "https://a/alerts"
    assert "headers" not in updater
